# --- 1. Despliegue (Deployment) para orders-service ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          #image: tunombredeusuario/plataforma-orders-service:latest # <-- Imagen para el servicio de órdenes
          image: plataforma-orders-service:latest # <-- Nombre local
          imagePullPolicy: Never               # <-- Añadir esta línea
          ports:
            - containerPort: 3002 # <-- Puerto del contenedor de órdenes
          env: # Asumo que usa las mismas variables de entorno y secretos
            - name: DB_HOST
              #value: "nombre-de-tu-bd-en-la-nube.com" # <-- Ya no es 'postgres-db'
              value: "host.docker.internal"
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: "plataforma_retail_orders"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret

---
# --- 2. Servicio (Service) para orders-service ---
apiVersion: v1
kind: Service
metadata:
  name: orders-service # Este es el nombre DNS (ej. http://orders-service)
spec:
  type: LoadBalancer 
  selector:
    app: orders-service
  ports:
    - protocol: TCP
      port: 3002       # Puerto público
      targetPort: 3002 # <-- Puerto del contenedor de órdenes