# --- 1. Despliegue (Deployment) para reports-service ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reports-service
  template:
    metadata:
      labels:
        app: reports-service
    spec:
      containers:
        - name: reports-service
          #image: tunombredeusuario/plataforma-reports-service:latest # <-- Imagen para el servicio de reportes
          image: plataforma-reports-service:latest # <-- Nombre local
          imagePullPolicy: Never               # <-- Añadir esta línea
          ports:
            - containerPort: 3005 # <-- Puerto del contenedor de reportes
          env: # Asumo que usa las mismas variables de entorno y secretos
            - name: DB_HOST
              #value: "nombre-de-tu-bd-en-la-nube.com" # <-- Ya no es 'postgres-db'
              value: "host.docker.internal"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret

---
# --- 2. Servicio (Service) para reports-service ---
apiVersion: v1
kind: Service
metadata:
  name: reports-service # Este es el nombre DNS (ej. http://reports-service)
spec:
  type: LoadBalancer 
  selector:
    app: reports-service
  ports:
    - protocol: TCP
      port: 80       # Puerto público
      targetPort: 3005 # <-- Puerto del contenedor de reportes