# --- 1. Despliegue (Deployment) para suppliers-service ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: suppliers-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: suppliers-service
  template:
    metadata:
      labels:
        app: suppliers-service
    spec:
      containers:
        - name: suppliers-service
          #image: tunombredeusuario/plataforma-suppliers-service:latest # <-- Imagen para el servicio de proveedores
          image: plataforma-suppliers-service:latest # <-- Nombre local
          imagePullPolicy: Never               # <-- Añadir esta línea
          ports:
            - containerPort: 3003 # <-- Puerto del contenedor de proveedores
          env: # Asumo que usa las mismas variables de entorno y secretos
            - name: DB_HOST
              #value: "nombre-de-tu-bd-en-la-nube.com" # <-- Ya no es 'postgres-db'
              value: "host.docker.internal"
              # --- AÑADIR ESTAS DOS LÍNEAS ---
            - name: DB_PORT
              value: "5432" # El puerto de Postgres
            - name: DB_DATABASE
              value: "plataforma_retail_suppliers" # La base de datos correcta para Suppliers
            # -----------------------------------
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret

---
# --- 2. Servicio (Service) para suppliers-service ---
apiVersion: v1
kind: Service
metadata:
  name: suppliers-service # Este es el nombre DNS (ej. http://suppliers-service)
spec:
  type: LoadBalancer 
  selector:
    app: suppliers-service
  ports:
    - protocol: TCP
      port: 80       # Puerto público
      targetPort: 3003 # <-- Puerto del contenedor de proveedores